version: 2
registries:
  rubygems-server-rubygems-pkg-github-com-forward3d:
    type: rubygems-server
    url: https://rubygems.pkg.github.com/forward3d
    username: "${{secrets.RUBYGEMS_SERVER_RUBYGEMS_PKG_GITHUB_COM_FORWARD3D_USERNAME}}"
    password: "${{secrets.RUBYGEMS_SERVER_RUBYGEMS_PKG_GITHUB_COM_FORWARD3D_PASSWORD}}"

updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  registries:
  - rubygems-server-rubygems-pkg-github-com-forward3d
